[workspace]

members =[
    "elkato-common",
    "elkato-client",
    "elkato-proxy",
    "elkato-frontend",
]

[patch.crates-io]
patternfly-yew = { git = "https://github.com/ctron/patternfly-yew", branch = "main" }
