[package]
name = "elkato-frontend"
version = "0.1.0"
authors = ["Jens Reimann <jreimann@redhat.com>"]
edition = "2018"
readme = "README.md"
description = "Addon-on frontend for Elkato"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1"
yew = "0.17"
wasm-bindgen = "0.2"

elkato-common = { path = "../elkato-common" }

chrono = { version = "0.4", features = ["wasmbind"] }
chrono-tz = "0.5"

log = "0.4"
wasm-logger = "0.2"

headers = "0.3"

patternfly-yew = { git = "https://github.com/ctron/patternfly-yew", branch = "main" }

[patch.'https://github.com/ctron/patternfly-yew']
#patternfly-yew = { path = "../../patternfly-yew" }
