---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ubi8
spec:
  tags:
    - from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi8
      name: latest
      importPolicy:
        scheduled: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ubi8-minimal
spec:
  tags:
    - from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi8-minimal
      name: latest
      importPolicy:
        scheduled: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: rust
spec:
  tags:
    - from:
        kind: DockerImage
        name: docker.io/library/rust
      name: latest
      importPolicy:
        scheduled: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: elkato-proxy
