---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ubi8
spec:
  tags:
    - from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi8
      name: latest
      importPolicy:
        scheduled: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ubi8-minimal
spec:
  tags:
    - from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi8-minimal
      name: latest
      importPolicy:
        scheduled: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: fedora
spec:
  tags:
    - from:
        kind: DockerImage
        name: docker.io/library/fedora:32
      name: latest
      importPolicy:
        scheduled: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: rust
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      annotations: null
      from:
        kind: DockerImage
        name: docker.io/library/rust
      generation: 2
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: elkato-proxy
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: elkato-frontend