apiVersion: apps/v1
kind: Deployment
metadata:
  name: elkato-proxy
  labels:
    app: elkato-proxy
  annotations:
    image.openshift.io/triggers: |
      [
        {
          "from": {
            "kind":"ImageStreamTag",
            "name":"elkato-proxy:latest"
          },
          "fieldPath":"spec.template.spec.containers[?(@.name==\"proxy\")].image"
        }
      ]
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elkato-proxy
  template:
    metadata:
      labels:
        app: elkato-proxy
    spec:
      containers:
        - name: proxy
          image: elkato-proxy
          env:
            - name: RUST_LOG
              value: info
            - name: BIND_ADDR
              value: "0.0.0.0:8080"
          ports:
            - containerPort: 8080
              name: api
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
