kind: Service
apiVersion: v1
metadata:
  name: elkato
  labels:
    app: elkato-proxy
spec:
  selector:
    app: elkato-proxy
  ports:
    - name: api
      protocol: TCP
      port: 8080
      targetPort: api
